spring:
  datasource:
    url: jdbc:mysql://192.168.163.8:3306/spring_boot_prac04
    username: prac04_user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8085